name = "ez-trading-forecast-cron"
main = "src/worker.js"
compatibility_date = "2026-06-05"
workers_dev = true

[triggers]
crons = ["*/15 2-8 * * 1-5"]

[vars]
TRIGGER_URL = "https://ez-trading.vercel.app/api/trigger-forecast"
