window.SCREENING_DEEP_ANALYSIS = {
  "memos": [
    {
      "symbol": "BFC",
      "status": "THEO DÕI",
      "currentPrice": 56.4,
      "priceAsOf": "2026-05-28",
      "targetPrice": 68.76,
      "stopPrice": 51.57,
      "suggestedWeight": null,
      "industry": "SX Nhựa - Hóa chất",
      "sleeve": "non_financial",
      "upsidePct": 21.91,
      "downsidePct": 8.56,
      "plan": "Giá thị trường phục vụ bảng lệnh mới nhất.",
      "reasons": []
    },
    {
      "symbol": "DXP",
      "status": "THEO DÕI",
      "currentPrice": 13.4,
      "priceAsOf": "2026-06-01",
      "targetPrice": 17.16,
      "stopPrice": 11.88,
      "suggestedWeight": null,
      "industry": "Vận tải - kho bãi",
      "sleeve": "non_financial",
      "upsidePct": 28.06,
      "downsidePct": 11.34,
      "plan": "Giá thị trường phục vụ bảng lệnh mới nhất.",
      "reasons": []
    },
    {
      "symbol": "GEE",
      "status": "THEO DÕI",
      "currentPrice": 101.4,
      "priceAsOf": "2026-06-01",
      "targetPrice": 142.051,
      "stopPrice": 94.874,
      "suggestedWeight": null,
      "industry": "Thiết bị điện",
      "sleeve": "non_financial",
      "upsidePct": 40.09,
      "downsidePct": 6.44,
      "plan": "Giá thị trường phục vụ bảng lệnh mới nhất.",
      "reasons": []
    },
    {
      "symbol": "VIC",
      "status": "THEO DÕI",
      "currentPrice": 208.0,
      "priceAsOf": "2026-06-01",
      "targetPrice": 255.278,
      "stopPrice": 187.661,
      "suggestedWeight": null,
      "industry": "Bất động sản",
      "sleeve": "non_financial",
      "upsidePct": 22.73,
      "downsidePct": 9.78,
      "plan": "Giá thị trường phục vụ bảng lệnh mới nhất.",
      "reasons": []
    },
    {
      "symbol": "PVP",
      "status": "THEO DÕI",
      "currentPrice": 17.7,
      "priceAsOf": "2026-06-01",
      "targetPrice": 24.186,
      "stopPrice": 15.138,
      "suggestedWeight": null,
      "industry": "Vận tải - kho bãi",
      "sleeve": "oil_gas",
      "upsidePct": 36.64,
      "downsidePct": 14.47,
      "plan": "Giá thị trường phục vụ bảng lệnh mới nhất.",
      "reasons": []
    }
  ],
  "strategyPolicies": [
    {
      "key": "r46_bear_stop_mcore",
      "label": "R46 Bear Stop",
      "historicalCagr": 76.47,
      "historicalSharpe": 2.19,
      "historicalMaxDrawdown": -25.62,
      "totalReturn": 2029.95,
      "lastUpdate": "2026-05-25",
      "stopMode": "R46: M-core weekly target, gap/pullback execution, 5% stop only in bear regime, strict daily 100-lot, fixed NAV 3 ty, cap 20% ADV.",
      "totalSuggestedWeight": 5.5,
      "cashBuffer": 94.5,
      "componentWeight": 100.0,
      "productionAudit": {
        "status": "R46_BEAR_STOP_15BPS",
        "passVni20": 6,
        "passVni30": 6,
        "fullPassVni20": 7,
        "fullPassVni30": 7,
        "cagr": 76.47,
        "maxDrawdown": -25.62,
        "minEdgeVsVni": 32.76923021119122,
        "slippageBps": 15,
        "regimeStopSells": 18,
        "failYears": []
      },
      "note": "R46 Bear Stop: user-approved dashboard default for NAV <5 ty under 15bps execution. Dashboard performance is displayed from 2021 onward; 20bps stress drops VNI+30 to 5/6.",
      "methodology": {
        "status": "R46 Bear Stop - dashboard default",
        "target": "Policy theo scope live NAV <5 ty; muc tieu dashboard la VNI+20/VNI+30 6/6 giai doan 2021-hien tai o 15bps.",
        "entry": "Tin hieu tuan; mua theo R46 execution: gap toi da 9%, buffer 1.5%, cho pullback toi da 2 phien; lenh lam tron lo 100.",
        "selection": "Dung M-core target/retention, cap thanh khoan 20% ADV tai NAV 3 ty; khong ETF/bond/margin/short.",
        "risk": "15bps duoc anh chap nhan cho dashboard. Neu chi phi thuc te len 20bps, VNI+30 recent con 5/6 nen can track slippage that.",
        "audit": "R46 Bear Stop: user-approved dashboard default for NAV <5 ty under 15bps execution. Dashboard performance is displayed from 2021 onward; 20bps stress drops VNI+30 to 5/6.",
        "cards": [
          [
            "1. Vũ trụ cổ phiếu (Universe)",
            "Sàn áp dụng: HOSE, HNX, UPCoM. Chỉ cổ phiếu thường, KHÔNG ETF, trái phiếu, margin, bán khống, phái sinh. Tiền chưa dùng để cash, lãi 0%. Mã phải có thanh khoản trung bình 20 phiên (ADV20) tối thiểu 5 tỷ đồng/ngày. Có nhánh ngoại lệ cho mã 3-5 tỷ/ngày nếu composite score ≥ 70 và (ret13 ≥ 20% hoặc ret26 ≥ 30% hoặc đang trong cụm breakout ngành). Date constraint: score chỉ được tính từ dữ liệu có trước ngày tín hiệu (no future leak)."
          ],
          [
            "2. Bộ lọc điểm số (Score Gates)",
            "Mỗi cổ phiếu có 7 score thành phần range 0-100 (fa_rank: tài chính; mom_rank: động lượng; rs_rank: sức mạnh tương đối; high_rank: gần đỉnh 52W; flow_rank: dòng tiền; industry_score: ngành; tech_score: kỹ thuật nền). Hard gates: composite_score ≥ 70 (tổng hợp BCTC + định giá + momentum theo công thức 0.30×Quality + 0.25×Valuation + 0.20×Catalyst + 0.25×Technical), industry_score ≥ 40, industry rank ≤ top 10, hard_gate==PASS (ROE bank ≥ 12%, ROA bank ≥ 0.8%, D/E phi ngân hàng ≤ 400%, không gap data), RSI14 trong khoảng 35-78 (mở rộng tới 95 nếu mã đang breakout sát đỉnh 52W)."
          ],
          [
            "3. Điều kiện MUA (Entry — family sector_cluster)",
            "Sau khi qua universe + score gates, candidate được chấm score sector_cluster: ưu tiên mã sát đỉnh 52W (high_rank weight 0.45), cộng điểm mạnh cho cụm ngành breakout (35 điểm khi cluster_breakout_flag=1, +6×cluster_strength_4w), cộng momentum ret4 (14×ret4). Cluster breakout active khi trong cùng ngành có ≥ 2 mã đồng thời gần đỉnh ≥ 97% và ret4 ≥ -2%. Rule one-per-industry: nếu bật, mỗi ngành chỉ giữ 1 mã có tech_score cao nhất, chống concentration."
          ],
          [
            "4. Quy mô vị thế (Position Sizing)",
            "Max holdings: 5 mã. Max weight per stock (M-core cap): 55% per signal date. Cap thanh khoản (R18 NAV-aware): max_weight_by_liq = (20% × ADV20) / NAV_deployment 3 tỷ; final weight = min(M-core weight, max_weight_by_liq). Trung bình exposure thực tế ~60%; cash residual cao trong tuần regime yếu. Không có riskoff exposure floor — cash buffer có thể lên 95%+ (như tuần 25/05/2026: MSB 5.525% + cash 94.475%)."
          ],
          [
            "5. Điều kiện BÁN (Exit)",
            "Ba lớp: (a) Weekly rebalance: mỗi thứ 2, nếu weight hiện tại vượt target + 0.1% NAV thì bán phần dư tại giá mở cửa; (b) T+2.5 settle: mỗi lot phải giữ tối thiểu 4 phiên trước khi được bán (HOSE rule); (c) Bear regime daily stop 5%: nếu regime hôm nay = bear VÀ lot đã qua T+2.5 VÀ low_today ≤ entry × 0.95 → bán tại min(open, entry × 0.95). KHÔNG có stop trong regime bull/recovery/sideways."
          ],
          [
            "6. Regime Gate (M-core Phase 1 v4)",
            "Classifier weekly phân loại VN-Index thành 5 trạng thái theo priority. BEAR: vni_ret_13w < -5% HOẶC (vni_ret_4w < -8% VÀ breadth_top200 < 30%). BULL_BROAD: breadth_top200 > 25% VÀ vni_ret_13w > 8% VÀ dispersion_4w < 15% VÀ vni_ret_4w > 0. BULL_NARROW: mega_cap_leadership > 8% VÀ vni_ret_13w > 3% VÀ breadth_top200 < 50% VÀ vni_ret_4w > 0. RECOVERY: breadth_recovery_2w ≥ 1 VÀ vni_ret_4w > 0 VÀ vni_ret_13w < 0. SIDEWAYS: mặc định. Daily date → weekly regime gần nhất qua backward asof (no future leak)."
          ],
          [
            "7. Cash overlay (passive)",
            "Không có rule \"force 100% cash\" khi VNI rơi. Cash xuất hiện tự nhiên qua filter: khi regime weak, số mã qua được score gates giảm → sum target weight giảm → phần còn lại = cash. Cash yield giả định 0% (không gửi TGTK/bond — constraint của user). Model luôn cho phép giữ vị thế nếu có mã pass gate, không tự ý đứng ngoài."
          ],
          [
            "8. Rebalance & Execution (R23 flexible exec)",
            "Tần suất: signal generate tối Chủ Nhật (sau Friday close), execute Monday. Quy tắc: nếu Monday open ≤ Friday close × 1.09 → mua tại open (HOSE thực tế cap ở ~6.5% do biên độ sàn 7%). Nếu gap > 9% → chờ pullback trong 2 phiên kế tiếp, limit = Friday close × 1.015. Nếu trong window low ≤ limit → fill tại min(open, limit). Hết window không khớp → skip (MISS_BUY). Lot size: 100 cổ phiếu, làm tròn xuống. Settlement T+2.5."
          ],
          [
            "9. Chi phí giao dịch",
            "Phí buy: 0.15% phí + 0.15% slippage = 0.30% per side. Phí sell: 0.15% phí + 0.10% thuế TNCN + 0.15% slippage = 0.40% per side. Dashboard giả định extra slippage 15bps/side. Robust ở 15-18bps; tại 20bps recent +30pp gate giảm còn 5/6. Live broker phải đạt cost ≤ 18bps/side để giữ gate strict."
          ],
          [
            "10. Hiệu suất verified (2021-2026)",
            "CAGR 76.47%, MaxDD -25.62%, Sharpe 2.19. Pass +30pp 6/6 năm: 2021 +153.93pp, 2022 +67.24pp, 2023 +34.34pp, 2024 +45.95pp, 2025 +33.11pp, 2026 YTD +32.77pp. T+2.5 violations: 0/1,821 trades. Full 2016-2026: CAGR 46.75%, pass +30pp 7/11 (fail 2016/2017/2019/2020 — pre-strategy era)."
          ]
        ]
      },
      "holdings": [
        {
          "symbol": "MSB",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "R46_BEAR_STOP",
          "suggestedWeight": 5.5,
          "currentPrice": 14.85,
          "priceAsOf": "2026-06-01",
          "signalDate": "2026-05-25",
          "entryDate": "2026-05-25",
          "entryPrice": 14.084,
          "fillMode": "r46_gap_pullback_bear_stop_policy",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 20.5,
          "stopPrice": 12.25,
          "modelShares": 3800,
          "copyShares": 3800,
          "modelValueMil": 55.2,
          "currentValueMil": 56.4,
          "costMil": 53.5,
          "currentPnlMil": 2.9,
          "currentPnlPct": 5.44,
          "industry": "Ngân hàng",
          "sleeve": "bank",
          "upsidePct": 38.05,
          "downsidePct": 17.51,
          "plan": "R46 Bear Stop dang nam 3,800 co phieu MSB quy doi theo NAV 1 ty.",
          "reasons": [
            "R46 Bear Stop: M-core target, R46 execution gap 9%, buffer 1.5%, pullback 2 phien.",
            "Stop 5% chi bat khi Phase1 v4 regime = bear; binh thuong khong dung base stop.",
            "Anh chap nhan 15bps cho dashboard vi live NAV <5 ty; Claude audit PASS va plateau 4/4 PASS."
          ]
        }
      ],
      "plannedOrders": {
        "asOf": "2026-06-01",
        "planDate": "2026-06-01",
        "stage": "live_window",
        "source": "current_policy",
        "entryGapThresholdPct": 9.0,
        "priceLimitAware": true,
        "priceLimitGuardPct": 0.5,
        "pullbackDays": 2,
        "summary": "Không có mua/bán mới cho 2026-06-01; hiện là kế hoạch giữ danh mục và theo dõi giá.",
        "rows": [
          {
            "planDate": "2026-06-01",
            "symbol": "MSB",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 14.85,
            "priceAsOf": "2026-06-01",
            "entryPrice": 14.084,
            "referenceClose": 15.3,
            "referenceDate": "2026-05-29",
            "maxBuyPrice": 16.294,
            "limitPrice": 15.529,
            "gapPct": -2.94,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 5.5,
            "targetWeight": 5.5,
            "deltaWeight": 0.0,
            "currentCopyShares": 3800,
            "targetCopyShares": 3800,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 20.5,
            "stopPrice": 12.25,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          }
        ]
      }
    },
    {
      "key": "r23_nav3b_mcore",
      "label": "R23_NAV3B",
      "historicalCagr": 69.32,
      "historicalSharpe": 2.14,
      "historicalMaxDrawdown": -26.79,
      "totalReturn": 1604.86,
      "lastUpdate": "2026-05-25",
      "stopMode": "R23: M-core weekly target, strict daily 100-lot, fixed deployment NAV 3 ty, cap 20% ADV.",
      "totalSuggestedWeight": 5.5,
      "cashBuffer": 94.5,
      "componentWeight": 100.0,
      "productionAudit": {
        "status": "R23_NAV3B",
        "passVni20": 6,
        "passVni30": 6,
        "cagr": 69.32,
        "maxDrawdown": -26.79,
        "minEdgeVsVni": 30.56043151973222,
        "slippageBps": 15,
        "failYears": []
      },
      "note": "R23_NAV3B: fixed live NAV 3 ty, cap 20% ADV. Recent 2021-2026 VNI+20 6/6 den 30bps; older 2016/2017/2019/2020 khong dat VNI+20.",
      "methodology": {
        "status": "R23_NAV3B",
        "target": "Dashboard policy theo scope live NAV <=3 ty; muc tieu chinh la VNI+20 6/6 giai doan 2021-2026.",
        "entry": "Tin hieu tuan; khop strict daily 100-lot voi chi phi 15bps extra moi chieu trong so chinh.",
        "selection": "M-core BCTC-assisted + conditional retention, co cap thanh khoan theo 20% ADV tai NAV 3 ty.",
        "risk": "MaxDD gan -29% o 15bps; stress 30bps van giu VNI+20 6/6 nhung VNI+30 chi con 4/6.",
        "audit": "R23_NAV3B: fixed live NAV 3 ty, cap 20% ADV. Recent 2021-2026 VNI+20 6/6 den 30bps; older 2016/2017/2019/2020 khong dat VNI+20."
      },
      "holdings": [
        {
          "symbol": "MSB",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "R23_NAV3B",
          "suggestedWeight": 5.5,
          "currentPrice": 14.85,
          "priceAsOf": "2026-06-01",
          "signalDate": "2026-05-25",
          "entryDate": "2026-05-25",
          "entryPrice": 14.081,
          "fillMode": "R23_fixed_NAV3B_policy",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 20.5,
          "stopPrice": 12.25,
          "modelShares": 3800,
          "copyShares": 3800,
          "modelValueMil": 55.2,
          "currentValueMil": 56.4,
          "costMil": 53.5,
          "currentPnlMil": 2.9,
          "currentPnlPct": 5.46,
          "industry": "Ngân hàng",
          "sleeve": "bank",
          "upsidePct": 38.05,
          "downsidePct": 17.51,
          "plan": "R23_NAV3B dang nam 3,800 co phieu MSB quy doi theo NAV 1 ty.",
          "reasons": [
            "R23_NAV3B: M-core + conditional retention, co dinh live NAV 3 ty, cap 20% ADV.",
            "2021-2026 dat VNI+20 6/6 o stress 30bps; 15bps dat ca VNI+20 6/6 va VNI+30 6/6.",
            "Khong phai bang chung full-history 2012-2026; day la policy dashboard theo scope NAV nho anh vua chap nhan."
          ]
        }
      ],
      "plannedOrders": {
        "asOf": "2026-06-01",
        "planDate": "2026-06-01",
        "stage": "live_window",
        "source": "current_policy",
        "entryGapThresholdPct": 9.0,
        "priceLimitAware": true,
        "priceLimitGuardPct": 0.5,
        "pullbackDays": 2,
        "summary": "Không có mua/bán mới cho 2026-06-01; hiện là kế hoạch giữ danh mục và theo dõi giá.",
        "rows": [
          {
            "planDate": "2026-06-01",
            "symbol": "MSB",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 14.85,
            "priceAsOf": "2026-06-01",
            "entryPrice": 14.081,
            "referenceClose": 15.3,
            "referenceDate": "2026-05-29",
            "maxBuyPrice": 16.294,
            "limitPrice": 15.3,
            "gapPct": -2.94,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 5.5,
            "targetWeight": 5.5,
            "deltaWeight": 0.0,
            "currentCopyShares": 3800,
            "targetCopyShares": 3800,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 20.5,
            "stopPrice": 12.25,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          }
        ]
      }
    },
    {
      "key": "technical_t2_vni30_v13",
      "label": "T2 VNI+30 Research",
      "historicalCagr": 77.79,
      "historicalSharpe": 1.54,
      "historicalMaxDrawdown": -36.98,
      "totalReturn": 2106.93,
      "lastUpdate": "2026-05-22",
      "stopMode": "Bán/giảm tỷ trọng khi target tuần mới đổi; chỉ mua trong vùng limit theo close thứ 6; strict T+2.5 và lô 100 cổ.",
      "totalSuggestedWeight": 72.8,
      "cashBuffer": 27.2,
      "componentWeight": 100.0,
      "productionAudit": {
        "status": "RESEARCH_ONLY",
        "passVni20": 6,
        "passVni30": 6,
        "cagr": 77.79023378192078,
        "minEdgeVsVni": 31.461606769889087,
        "failYears": [],
        "stressVni20Pass6Cells": 6,
        "stressVni30Pass6Cells": 2
      },
      "note": "T2 V13 đạt VNI+20 6/6 và VNI+30 6/6 trong strict daily-lot, CAGR 77.8%, min edge 31.5 điểm %. Hiển thị để anh paper-trade/review; chưa mở production vì còn cảnh báo single-position cap 85% và VNI+30 nhạy với stress chi phí.",
      "methodology": {
        "status": "Research/Paper-trade candidate - chưa production",
        "target": "Beat VN-Index +30 điểm phần trăm mỗi năm; sau khi review sạch mới cân nhắc production.",
        "entry": "Mua bằng limit quanh close thứ 6, core +1%, secondary +3%, không mua đuổi nếu vượt vùng.",
        "selection": "Pure technical state machine, không BCTC, không ngành, không year/ticker rescue.",
        "risk": "Còn rủi ro tập trung vị thế và nhạy chi phí; dashboard đang hiển thị để theo dõi có kiểm soát.",
        "audit": "T2 V13 đạt VNI+20 6/6 và VNI+30 6/6 trong strict daily-lot, CAGR 77.8%, min edge 31.5 điểm %. Hiển thị để anh paper-trade/review; chưa mở production vì còn cảnh báo single-position cap 85% và VNI+30 nhạy với stress chi phí.",
        "cards": [
          [
            "1. Tài sản được phép",
            "Chỉ cổ phiếu thường HOSE/HNX/UPCoM trong dữ liệu giá sạch. Không ETF, không trái phiếu, không margin, không bán khống. Phần không mua để cash, lãi cash = 0%."
          ],
          [
            "2. Mục tiêu kiểm tra",
            "Gate nghiên cứu hiện tại: mỗi năm phải hơn VN-Index ít nhất 30 điểm phần trăm. V13 đang đạt 6/6 năm trên daily-lot, min edge 31,46 điểm phần trăm."
          ],
          [
            "3. Dữ liệu đầu vào",
            "Thuần kỹ thuật: giá OHLCV, thanh khoản 20 phiên, sức mạnh tương đối nhiều khung, số mã tăng/giảm của thị trường và trạng thái VN-Index. Không dùng BCTC nên không có lỗi delay ngày công bố."
          ],
          [
            "4. Thanh khoản",
            "Mã phải có giá trị giao dịch bình quân 20 phiên tối thiểu 3 tỷ/ngày. Lệnh được mô phỏng theo lô 100 cổ phiếu và có kiểm tra khả năng thực thi theo thanh khoản."
          ],
          [
            "5. State thị trường",
            "Mỗi cuối tuần model phân loại trạng thái như recovery, risk-off hoặc trend bằng VNI/breadth. Trạng thái chỉ đổi sau tín hiệu đã chốt cuối tuần, không biết trước diễn biến tuần sau."
          ],
          [
            "6. Chấm điểm cổ phiếu",
            "Ưu tiên cổ phiếu có sức mạnh tương đối tốt, giá còn giữ xu hướng, thanh khoản cải thiện và không bị breadth shock. Cùng một công thức dùng cho toàn bộ 2021-2026, không có rule riêng theo năm hay theo mã."
          ],
          [
            "7. Chọn danh mục",
            "Tối đa 3 mã mục tiêu. Core sleeve có thể lên tới 85% NAV, secondary technical sleeve khoảng 8,5% mỗi mã. Đây là điểm mạnh về CAGR nhưng cũng là cảnh báo tập trung vị thế."
          ],
          [
            "8. Vùng mua",
            "Lệnh mua dùng close thứ 6 làm tham chiếu. Core thường mua tối đa quanh close +1%; secondary tối đa quanh close +3%. Nếu thứ 2 tăng vượt vùng này thì chờ T2-T4 quay về vùng mua, không quay lại thì bỏ qua."
          ],
          [
            "9. Bán và rebalance",
            "Bán khi target tuần mới giảm tỷ trọng hoặc đổi mã. Rebalance band 12 điểm phần trăm để tránh đảo lệnh quá nhiều. Lệnh bán luôn kiểm tra T+2.5 trong backtest."
          ],
          [
            "10. Chi phí kiểm tra",
            "Số chính dùng trượt giá 0,15% mỗi chiều. Stress 0,20%-0,30% vẫn giữ VNI+20 khá tốt nhưng VNI+30 chỉ pass một phần stress, nên chưa gọi là production an toàn tuyệt đối."
          ],
          [
            "11. Rủi ro cần theo dõi",
            "MaxDD khoảng -37%, vị thế đơn tối đa 85%, remove-top-winner còn làm VNI+30 rơi xuống 4/6. Vì vậy dashboard gắn nhãn Research/Paper-trade cho tới khi Claude review độc lập xong."
          ]
        ]
      },
      "holdings": [
        {
          "symbol": "MSB",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO T2 VNI+30",
          "suggestedWeight": 72.8,
          "currentPrice": 14.85,
          "priceAsOf": "2026-06-01",
          "signalDate": "2026-05-22",
          "entryDate": "2026-05-18",
          "entryPrice": 13.8,
          "fillMode": "limit_zone_daily_lot",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 20.5,
          "stopPrice": 12.25,
          "modelShares": 49000,
          "copyShares": 49000,
          "modelValueMil": 727.6,
          "currentValueMil": 727.6,
          "costMil": 676.2,
          "currentPnlMil": 51.4,
          "currentPnlPct": 7.61,
          "industry": "Ngân hàng",
          "sleeve": "Pure technical T2",
          "upsidePct": 38.05,
          "downsidePct": 17.51,
          "plan": "Model T2 đang nắm 49,000 cổ phiếu MSB quy đổi NAV 1 tỷ, giá vốn bình quân 13.80k.",
          "reasons": [
            "Pure technical: chỉ dùng giá, thanh khoản, sức mạnh tương đối, breadth và trạng thái thị trường tới cuối tuần trước.",
            "Không dùng BCTC, không dùng ngành hiện tại, không ETF/bond/margin/short.",
            "Backtest strict daily-lot: lệnh chẵn 100 cổ, có T+2.5 và trượt giá 0,15% mỗi chiều."
          ]
        }
      ],
      "plannedOrders": {
        "asOf": "2026-06-01",
        "planDate": "2026-05-25",
        "signalDate": "2026-05-22",
        "stage": "closed_window",
        "source": "technical_t2_weekly_targets",
        "entryGapThresholdPct": null,
        "priceLimitAware": true,
        "pullbackDays": 2,
        "summary": "Kế hoạch 2026-05-25 đã được đánh giá theo giá đến 2026-06-01: 3 lệnh đã xử lý.",
        "rows": [
          {
            "planDate": "2026-05-25",
            "signalDate": "2026-05-22",
            "symbol": "MSB",
            "exchange": "HOSE",
            "action": "BÁN 1 PHẦN",
            "status": "ĐÃ BÁN",
            "currentPrice": 14.85,
            "priceAsOf": "2026-06-01",
            "entryPrice": 13.8,
            "referenceClose": 14.4,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 14.544,
            "limitPrice": 14.4,
            "gapPct": 3.12,
            "executionDate": "2026-05-25",
            "executionPrice": 14.35,
            "executionMode": "open",
            "executed": true,
            "baseGapThresholdPct": 1.0,
            "effectiveGapThresholdPct": 1.0,
            "currentWeight": 72.77,
            "targetWeight": 44.2,
            "deltaWeight": -28.56,
            "currentCopyShares": 49000,
            "targetCopyShares": 29700,
            "orderShares": 19300,
            "orderValueMil": 277.0,
            "targetPrice": 20.5,
            "stopPrice": 12.25,
            "note": "Đã bán mở cửa @ 14.35k theo kế hoạch 2026-05-25."
          },
          {
            "planDate": "2026-05-25",
            "signalDate": "2026-05-22",
            "symbol": "VHM",
            "exchange": "HOSE",
            "action": "MUA MỚI",
            "status": "ĐÃ KHỚP",
            "currentPrice": 156.5,
            "priceAsOf": "2026-05-26",
            "entryPrice": 156.5,
            "referenceClose": 153.8,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 158.414,
            "limitPrice": 153.8,
            "gapPct": 1.76,
            "executionDate": "2026-05-25",
            "executionPrice": 155.0,
            "executionMode": "open",
            "executed": true,
            "baseGapThresholdPct": 3.0,
            "effectiveGapThresholdPct": 3.0,
            "currentWeight": 0.0,
            "targetWeight": 8.5,
            "deltaWeight": 8.5,
            "currentCopyShares": 0,
            "targetCopyShares": 500,
            "orderShares": 500,
            "orderValueMil": 77.5,
            "targetPrice": 204.4,
            "stopPrice": 137.2,
            "note": "Đã khớp mở cửa @ 155.00k; dùng kế hoạch 2026-05-25, tín hiệu 2026-05-22."
          },
          {
            "planDate": "2026-05-25",
            "signalDate": "2026-05-22",
            "symbol": "VIC",
            "exchange": "HOSE",
            "action": "MUA MỚI",
            "status": "ĐÃ KHỚP",
            "currentPrice": 208.0,
            "priceAsOf": "2026-06-01",
            "entryPrice": 208.0,
            "referenceClose": 216.5,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 222.995,
            "limitPrice": 216.5,
            "gapPct": -3.93,
            "executionDate": "2026-05-25",
            "executionPrice": 216.6,
            "executionMode": "open",
            "executed": true,
            "baseGapThresholdPct": 3.0,
            "effectiveGapThresholdPct": 3.0,
            "currentWeight": 0.0,
            "targetWeight": 8.5,
            "deltaWeight": 8.5,
            "currentCopyShares": 0,
            "targetCopyShares": 400,
            "orderShares": 400,
            "orderValueMil": 86.6,
            "targetPrice": 255.278,
            "stopPrice": 187.661,
            "note": "Đã khớp mở cửa @ 216.60k; dùng kế hoạch 2026-05-25, tín hiệu 2026-05-22."
          }
        ]
      }
    },
    {
      "key": "rank_best_full_tier_a",
      "label": "Best hiện tại - sạch",
      "historicalCagr": 19.88,
      "historicalSharpe": 0.83,
      "historicalMaxDrawdown": -34.15,
      "totalReturn": 615.64,
      "lastUpdate": "2026-05-11",
      "stopMode": "Bán khi điểm tổng hợp rơi dưới 50, mất xu hướng tuần 2 tuần liên tiếp, hoặc chạm stop-loss 12%. Khi VNI 8 tuần giảm mạnh, policy tăng cash.",
      "totalSuggestedWeight": 95.4,
      "cashBuffer": 4.6,
      "componentWeight": 100.0,
      "note": "Best sạch hiện tại: CAGR 19.88%, MaxDD -34.15%, beat VNI 5/6 năm 2021-2026; không đạt VNI+20/+30 6/6 nhưng rule tổng quát và audit sạch hơn các candidate overfit.",
      "methodology": {
        "status": "Best sạch hiện tại - được phép theo dõi/paper-trade",
        "target": "Ưu tiên rule bền, hạn chế overfit; mục tiêu thực tế là beat VNI dài hạn, chưa claim VNI+20/+30 6/6.",
        "entry": "Tín hiệu được chốt sau cuối tuần. Lệnh mua dùng giá tham chiếu cuối tuần, không đuổi giá nếu đầu tuần gap mạnh; chỉ đặt lệnh chẵn 100 cổ.",
        "selection": "Lọc cổ phiếu thường có thanh khoản đủ lớn, giá không quá thấp, xu hướng tuần còn tăng, RSI trong vùng 35-80, điểm tổng hợp >= 50; tối đa 6 mã, mỗi mã tối đa 20% NAV trước khi trôi giá.",
        "risk": "Có cash buffer 5%, stop-loss 12%, thoát khi điểm suy yếu hoặc xu hướng tuần gãy. Tiền mặt không tính lãi.",
        "audit": "Best sạch hiện tại: CAGR 19.88%, MaxDD -34.15%, beat VNI 5/6 năm 2021-2026; không đạt VNI+20/+30 6/6 nhưng rule tổng quát và audit sạch hơn các candidate overfit."
      },
      "holdings": [
        {
          "symbol": "DCM",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO BEST HIỆN TẠI",
          "suggestedWeight": 21.9,
          "currentPrice": 40.4,
          "priceAsOf": "2026-05-25",
          "signalDate": "2026-05-11",
          "entryDate": "2026-02-16",
          "entryPrice": 39.2,
          "fillMode": "weekly_close_signal",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 48.3,
          "stopPrice": 36.225,
          "modelShares": 4900,
          "copyShares": 4900,
          "modelValueMil": 218.6,
          "currentValueMil": 198.0,
          "costMil": 192.1,
          "currentPnlMil": 5.9,
          "currentPnlPct": 3.06,
          "industry": "SX Nhựa - Hóa chất",
          "sleeve": "non_financial",
          "upsidePct": 19.55,
          "downsidePct": 10.33,
          "plan": "Model sạch hiện đang nắm 4,900 cổ phiếu DCM quy đổi theo NAV 1 tỷ, giá vốn bình quân 39.20k.",
          "reasons": [
            "Policy này là best sạch hiện tại: rank_best_full, cash overlay, không ETF/bond/margin/short.",
            "NAV và lịch sử lấy từ equity_curve_honest.parquet để tránh lỗi MTM stale đã phát hiện.",
            "Đây là baseline production/paper-trade hợp lý nhất hiện tại, không phải candidate VNI+20/+30 đã bị overfit."
          ]
        },
        {
          "symbol": "VHC",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO BEST HIỆN TẠI",
          "suggestedWeight": 20.2,
          "currentPrice": 60.0,
          "priceAsOf": "2026-05-25",
          "signalDate": "2026-05-11",
          "entryDate": "2026-02-16",
          "entryPrice": 60.1,
          "fillMode": "weekly_close_signal",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 70.8,
          "stopPrice": 53.1,
          "modelShares": 3200,
          "copyShares": 3200,
          "modelValueMil": 202.3,
          "currentValueMil": 192.0,
          "costMil": 192.3,
          "currentPnlMil": -0.3,
          "currentPnlPct": -0.17,
          "industry": "Chế biến Thủy sản",
          "sleeve": "non_financial",
          "upsidePct": 18.0,
          "downsidePct": 11.5,
          "plan": "Model sạch hiện đang nắm 3,200 cổ phiếu VHC quy đổi theo NAV 1 tỷ, giá vốn bình quân 60.10k.",
          "reasons": [
            "Policy này là best sạch hiện tại: rank_best_full, cash overlay, không ETF/bond/margin/short.",
            "NAV và lịch sử lấy từ equity_curve_honest.parquet để tránh lỗi MTM stale đã phát hiện.",
            "Đây là baseline production/paper-trade hợp lý nhất hiện tại, không phải candidate VNI+20/+30 đã bị overfit."
          ]
        },
        {
          "symbol": "HHS",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO BEST HIỆN TẠI",
          "suggestedWeight": 18.8,
          "currentPrice": 11.85,
          "priceAsOf": "2026-05-25",
          "signalDate": "2026-05-11",
          "entryDate": "2026-04-27",
          "entryPrice": 13.3,
          "fillMode": "weekly_close_signal",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 13.8,
          "stopPrice": 10.35,
          "modelShares": 14900,
          "copyShares": 14900,
          "modelValueMil": 187.9,
          "currentValueMil": 176.6,
          "costMil": 198.2,
          "currentPnlMil": -21.6,
          "currentPnlPct": -10.9,
          "industry": "Bán buôn",
          "sleeve": "non_financial",
          "upsidePct": 16.46,
          "downsidePct": 12.66,
          "plan": "Model sạch hiện đang nắm 14,900 cổ phiếu HHS quy đổi theo NAV 1 tỷ, giá vốn bình quân 13.30k.",
          "reasons": [
            "Policy này là best sạch hiện tại: rank_best_full, cash overlay, không ETF/bond/margin/short.",
            "NAV và lịch sử lấy từ equity_curve_honest.parquet để tránh lỗi MTM stale đã phát hiện.",
            "Đây là baseline production/paper-trade hợp lý nhất hiện tại, không phải candidate VNI+20/+30 đã bị overfit."
          ]
        },
        {
          "symbol": "VCG",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO BEST HIỆN TẠI",
          "suggestedWeight": 14.8,
          "currentPrice": 20.85,
          "priceAsOf": "2026-05-25",
          "signalDate": "2026-05-11",
          "entryDate": "2026-04-27",
          "entryPrice": 22.9,
          "fillMode": "weekly_close_signal",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 24.66,
          "stopPrice": 18.495,
          "modelShares": 6700,
          "copyShares": 6700,
          "modelValueMil": 148.2,
          "currentValueMil": 139.7,
          "costMil": 153.4,
          "currentPnlMil": -13.7,
          "currentPnlPct": -8.95,
          "industry": "Xây dựng",
          "sleeve": "non_financial",
          "upsidePct": 18.27,
          "downsidePct": 11.29,
          "plan": "Model sạch hiện đang nắm 6,700 cổ phiếu VCG quy đổi theo NAV 1 tỷ, giá vốn bình quân 22.90k.",
          "reasons": [
            "Policy này là best sạch hiện tại: rank_best_full, cash overlay, không ETF/bond/margin/short.",
            "NAV và lịch sử lấy từ equity_curve_honest.parquet để tránh lỗi MTM stale đã phát hiện.",
            "Đây là baseline production/paper-trade hợp lý nhất hiện tại, không phải candidate VNI+20/+30 đã bị overfit."
          ]
        },
        {
          "symbol": "DPR",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO BEST HIỆN TẠI",
          "suggestedWeight": 11.1,
          "currentPrice": 41.65,
          "priceAsOf": "2026-05-25",
          "signalDate": "2026-05-11",
          "entryDate": "2026-01-05",
          "entryPrice": 36.75,
          "fillMode": "weekly_close_signal",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 49.68,
          "stopPrice": 37.26,
          "modelShares": 2500,
          "copyShares": 2500,
          "modelValueMil": 111.2,
          "currentValueMil": 104.1,
          "costMil": 91.9,
          "currentPnlMil": 12.2,
          "currentPnlPct": 13.33,
          "industry": "SX Nhựa - Hóa chất",
          "sleeve": "non_financial",
          "upsidePct": 19.28,
          "downsidePct": 10.54,
          "plan": "Model sạch hiện đang nắm 2,500 cổ phiếu DPR quy đổi theo NAV 1 tỷ, giá vốn bình quân 36.75k.",
          "reasons": [
            "Policy này là best sạch hiện tại: rank_best_full, cash overlay, không ETF/bond/margin/short.",
            "NAV và lịch sử lấy từ equity_curve_honest.parquet để tránh lỗi MTM stale đã phát hiện.",
            "Đây là baseline production/paper-trade hợp lý nhất hiện tại, không phải candidate VNI+20/+30 đã bị overfit."
          ]
        },
        {
          "symbol": "MSH",
          "exchange": "HOSE",
          "status": "MUA",
          "rating": "ĐANG NẮM THEO BEST HIỆN TẠI",
          "suggestedWeight": 8.6,
          "currentPrice": 35.0,
          "priceAsOf": "2026-05-25",
          "signalDate": "2026-05-11",
          "entryDate": "2026-03-23",
          "entryPrice": 34.565,
          "fillMode": "weekly_close_signal",
          "entryGapPct": 0.0,
          "sellableFrom": null,
          "isSellableNow": true,
          "targetPrice": 41.16,
          "stopPrice": 30.87,
          "modelShares": 2300,
          "copyShares": 2300,
          "modelValueMil": 85.6,
          "currentValueMil": 80.5,
          "costMil": 79.5,
          "currentPnlMil": 1.0,
          "currentPnlPct": 1.26,
          "industry": "SX Hàng gia dụng",
          "sleeve": "non_financial",
          "upsidePct": 17.6,
          "downsidePct": 11.8,
          "plan": "Model sạch hiện đang nắm 2,300 cổ phiếu MSH quy đổi theo NAV 1 tỷ, giá vốn bình quân 34.56k.",
          "reasons": [
            "Policy này là best sạch hiện tại: rank_best_full, cash overlay, không ETF/bond/margin/short.",
            "NAV và lịch sử lấy từ equity_curve_honest.parquet để tránh lỗi MTM stale đã phát hiện.",
            "Đây là baseline production/paper-trade hợp lý nhất hiện tại, không phải candidate VNI+20/+30 đã bị overfit."
          ]
        }
      ],
      "plannedOrders": {
        "asOf": "2026-05-25",
        "planDate": "2026-05-25",
        "stage": "live_window",
        "source": "current_policy",
        "entryGapThresholdPct": 9.0,
        "priceLimitAware": true,
        "priceLimitGuardPct": 0.5,
        "pullbackDays": 2,
        "summary": "Không có mua/bán mới cho 2026-05-25; hiện là kế hoạch giữ danh mục và theo dõi giá.",
        "rows": [
          {
            "planDate": "2026-05-25",
            "symbol": "DCM",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 40.4,
            "priceAsOf": "2026-05-25",
            "entryPrice": 39.2,
            "referenceClose": 41.6,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 44.304,
            "limitPrice": 41.6,
            "gapPct": -2.88,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 21.9,
            "targetWeight": 21.9,
            "deltaWeight": 0.0,
            "currentCopyShares": 4900,
            "targetCopyShares": 4900,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 48.3,
            "stopPrice": 36.225,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          },
          {
            "planDate": "2026-05-25",
            "symbol": "DPR",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 41.65,
            "priceAsOf": "2026-05-25",
            "entryPrice": 36.75,
            "referenceClose": 41.8,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 44.517,
            "limitPrice": 41.8,
            "gapPct": -0.36,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 11.1,
            "targetWeight": 11.1,
            "deltaWeight": 0.0,
            "currentCopyShares": 2500,
            "targetCopyShares": 2500,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 49.68,
            "stopPrice": 37.26,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          },
          {
            "planDate": "2026-05-25",
            "symbol": "HHS",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 11.85,
            "priceAsOf": "2026-05-25",
            "entryPrice": 13.3,
            "referenceClose": 11.95,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 12.727,
            "limitPrice": 11.95,
            "gapPct": -0.84,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 18.8,
            "targetWeight": 18.8,
            "deltaWeight": 0.0,
            "currentCopyShares": 14900,
            "targetCopyShares": 14900,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 13.8,
            "stopPrice": 10.35,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          },
          {
            "planDate": "2026-05-25",
            "symbol": "MSH",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 35.0,
            "priceAsOf": "2026-05-25",
            "entryPrice": 34.565,
            "referenceClose": 35.7,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 38.02,
            "limitPrice": 35.7,
            "gapPct": -1.96,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 8.6,
            "targetWeight": 8.6,
            "deltaWeight": 0.0,
            "currentCopyShares": 2300,
            "targetCopyShares": 2300,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 41.16,
            "stopPrice": 30.87,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          },
          {
            "planDate": "2026-05-25",
            "symbol": "VCG",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 20.85,
            "priceAsOf": "2026-05-25",
            "entryPrice": 22.9,
            "referenceClose": 21.0,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 22.365,
            "limitPrice": 21.0,
            "gapPct": -0.71,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 14.8,
            "targetWeight": 14.8,
            "deltaWeight": 0.0,
            "currentCopyShares": 6700,
            "targetCopyShares": 6700,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 24.66,
            "stopPrice": 18.495,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          },
          {
            "planDate": "2026-05-25",
            "symbol": "VHC",
            "exchange": "HOSE",
            "action": "GIỮ",
            "status": "DỰ KIẾN",
            "currentPrice": 60.0,
            "priceAsOf": "2026-05-25",
            "entryPrice": 60.1,
            "referenceClose": 59.0,
            "referenceDate": "2026-05-22",
            "maxBuyPrice": 62.835,
            "limitPrice": 59.0,
            "gapPct": 1.69,
            "baseGapThresholdPct": 9.0,
            "effectiveGapThresholdPct": 6.5,
            "currentWeight": 20.2,
            "targetWeight": 20.2,
            "deltaWeight": 0.0,
            "currentCopyShares": 3200,
            "targetCopyShares": 3200,
            "orderShares": 0,
            "orderValueMil": 0.0,
            "targetPrice": 70.8,
            "stopPrice": 53.1,
            "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
          }
        ]
      }
    }
  ],
  "defaultPolicy": "r46_bear_stop_mcore",
  "plannedOrders": {
    "asOf": "2026-06-01",
    "planDate": "2026-06-01",
    "stage": "live_window",
    "source": "current_policy",
    "entryGapThresholdPct": 9.0,
    "priceLimitAware": true,
    "priceLimitGuardPct": 0.5,
    "pullbackDays": 2,
    "summary": "Không có mua/bán mới cho 2026-06-01; hiện là kế hoạch giữ danh mục và theo dõi giá.",
    "rows": [
      {
        "planDate": "2026-06-01",
        "symbol": "MSB",
        "exchange": "HOSE",
        "action": "GIỮ",
        "status": "DỰ KIẾN",
        "currentPrice": 14.85,
        "priceAsOf": "2026-06-01",
        "entryPrice": 14.084,
        "referenceClose": 15.3,
        "referenceDate": "2026-05-29",
        "maxBuyPrice": 16.294,
        "limitPrice": 15.529,
        "gapPct": -2.94,
        "baseGapThresholdPct": 9.0,
        "effectiveGapThresholdPct": 6.5,
        "currentWeight": 5.5,
        "targetWeight": 5.5,
        "deltaWeight": 0.0,
        "currentCopyShares": 3800,
        "targetCopyShares": 3800,
        "orderShares": 0,
        "orderValueMil": 0.0,
        "targetPrice": 20.5,
        "stopPrice": 12.25,
        "note": "Tín hiệu kỳ tới không đổi mã này; tiếp tục giữ và theo dõi target/stop."
      }
    ]
  },
  "initialCapital": {
    "amount_vnd": 1000000000,
    "start_date": "2021-01-01"
  },
  "portfolioPlan": {
    "rule": "Dashboard này chỉ hiển thị lệnh copy theo policy đang chọn. Không trộn thêm tín hiệu screening rời rạc để tránh mâu thuẫn.",
    "nav_vnd": 1000000000
  }
};
