"""Daily execution simulator for the flexible VNI+30 candidate.

This is stricter than the weekly return proxy. Weekly target portfolios are
still generated by ``pass30_direct_search.run_policy`` from point-in-time
signals, but orders are executed on daily bars with:

- Monday/open-or-pullback buy logic.
- Pending buy windows that can extend beyond Wednesday.
- Per-lot T+2.5 sell availability, approximated conservatively as the third
  trading session after entry for open-price exits.
- Optional daily stop loss after a lot becomes sellable.

The simulator keeps cash and shares, so late fills do not double-count returns
or reuse capital before the position can be sold.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

import pass30_direct_search as ds


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = ROOT / "output" / "beat_vni30_parallel" / "g2_flexible_entry_hit_mutation_buffer" / "best_stock_only" / "config.json"
DEFAULT_LABEL_DIR = ROOT / "output" / "beat_vni30_parallel" / "claude_lane_f2"
DEFAULT_OUT = ROOT / "output" / "beat_vni30_parallel" / "g2_daily_execution_latency_search"
PRICE_LIMIT_BY_EXCHANGE = {
    "HOSE": 0.07,
    "HSX": 0.07,
    "HNX": 0.10,
    "UPCOM": 0.15,
}
PRICE_LIMIT_GUARD = 0.005


def atomic_temp_path(path: Path) -> Path:
    return path.with_name(f".{path.stem}.{os.getpid()}.tmp{path.suffix}")


def fsync_file(path: Path) -> None:
    with path.open("r+b") as handle:
        os.fsync(handle.fileno())


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = atomic_temp_path(path)
    with tmp.open("w", encoding="utf-8") as handle:
        handle.write(text)
        handle.flush()
        os.fsync(handle.fileno())
    tmp.replace(path)


def atomic_write_csv(df: pd.DataFrame, path: Path, **kwargs) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = atomic_temp_path(path)
    df.to_csv(tmp, **kwargs)
    fsync_file(tmp)
    tmp.replace(path)


def atomic_write_parquet(df: pd.DataFrame, path: Path, **kwargs) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = atomic_temp_path(path)
    df.to_parquet(tmp, **kwargs)
    fsync_file(tmp)
    tmp.replace(path)


def verify_saved_outputs(best_dir: Path, best: dict) -> bool:
    try:
        eq = pd.read_parquet(best_dir / "equity_curve_honest.parquet")
        if len(eq) < 1000 or "nav" not in eq.columns:
            return False
        if not np.isfinite(pd.to_numeric(eq["nav"], errors="coerce").iloc[-1]):
            return False
        payload = json.loads((best_dir / "config.json").read_text(encoding="utf-8"))
        return int(payload.get("metrics", {}).get("pass_vni30", -1)) == int(best.get("metrics", {}).get("pass_vni30", -2))
    except Exception:
        return False


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_hash_chain(best_dir: Path) -> bool:
    sums = best_dir / "sha256sums.txt"
    if not sums.exists():
        return False
    for raw in sums.read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        parts = raw.split()
        if len(parts) < 3:
            return False
        expected_hash, name, expected_size = parts[0], parts[1], int(parts[2])
        path = best_dir / name
        if not path.exists() or path.stat().st_size != expected_size:
            return False
        if sha256_file(path) != expected_hash:
            return False
    return True


def verify_json_files(best_dir: Path, names: list[str]) -> bool:
    for name in names:
        path = best_dir / name
        if path.exists():
            try:
                json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                return False
    return True


def write_companion_integrity_files(best_dir: Path, best: dict, best_eq: pd.DataFrame, best_trades: pd.DataFrame) -> None:
    metrics = dict(best.get("metrics", {}))
    eq_sorted = best_eq.copy()
    if len(eq_sorted) and "date" in eq_sorted:
        eq_sorted["date"] = pd.to_datetime(eq_sorted["date"])
        eq_sorted = eq_sorted.sort_values("date").reset_index(drop=True)
    equity_summary = {
        "rows": int(len(best_eq)),
        "start_date": str(eq_sorted["date"].iloc[0]) if len(eq_sorted) and "date" in eq_sorted else None,
        "end_date": str(eq_sorted["date"].iloc[-1]) if len(eq_sorted) and "date" in eq_sorted else None,
        "start_nav": float(eq_sorted["nav"].iloc[0]) if len(eq_sorted) and "nav" in eq_sorted else None,
        "end_nav": float(eq_sorted["nav"].iloc[-1]) if len(eq_sorted) and "nav" in eq_sorted else None,
        "avg_exposure": float(eq_sorted["exposure"].mean()) if len(eq_sorted) and "exposure" in eq_sorted else None,
        "max_exposure": float(eq_sorted["exposure"].max()) if len(eq_sorted) and "exposure" in eq_sorted else None,
        "min_cash": float(eq_sorted["cash"].min()) if len(eq_sorted) and "cash" in eq_sorted else None,
    }
    trade_summary = {
        "rows": int(len(best_trades)),
        "first_date": str(best_trades["date"].iloc[0]) if len(best_trades) and "date" in best_trades else None,
        "last_date": str(best_trades["date"].iloc[-1]) if len(best_trades) and "date" in best_trades else None,
        "side_counts": best_trades["side"].astype(str).value_counts().to_dict() if len(best_trades) and "side" in best_trades else {},
        "reason_counts": best_trades["reason"].astype(str).value_counts().to_dict() if len(best_trades) and "reason" in best_trades else {},
    }
    companion = {
        "strategy_type": best.get("strategy_type"),
        "metrics": metrics,
        "execution": best.get("execution", {}),
        "stress": best.get("stress", {}),
        "vni_yearly_convention": best.get("vni_yearly_convention"),
        "equity_summary": equity_summary,
        "trade_summary": trade_summary,
    }
    atomic_write_text(best_dir / "metrics.json", json.dumps(companion, indent=2, default=str))
    yearly_rows = []
    if len(eq_sorted) and "date" in eq_sorted and "nav" in eq_sorted:
        for year in range(2021, 2027):
            group = eq_sorted[eq_sorted["date"].dt.year == year]
            if group.empty:
                continue
            prev = eq_sorted[eq_sorted["date"] < pd.Timestamp(f"{year}-01-01")]
            start_nav = float(prev["nav"].iloc[-1]) if not prev.empty else float(group["nav"].iloc[0])
            end_nav = float(group["nav"].iloc[-1])
            yearly_rows.append({
                "year": year,
                "start_date": str(group["date"].iloc[0]),
                "end_date": str(group["date"].iloc[-1]),
                "start_nav": start_nav,
                "end_nav": end_nav,
                "strategy_return_pct": metrics.get(f"y{year}"),
                "vni_return_pct": metrics.get(f"vni_y{year}"),
                "edge_vs_vni_pp": metrics.get(f"edge_y{year}"),
                "pass_vni30": metrics.get(f"pass_vni30_y{year}"),
            })
    atomic_write_text(
        best_dir / "equity_curve_yearly.json",
        json.dumps(
            {
                "vni_yearly_convention": best.get("vni_yearly_convention"),
                "rows": yearly_rows,
            },
            indent=2,
            default=str,
        ),
    )
    files = [
        "config.json",
        "daily_execution_trades.csv",
        "equity_curve_honest.parquet",
        "metrics.json",
        "equity_curve_yearly.json",
    ]
    lines = []
    for name in files:
        path = best_dir / name
        if path.exists():
            lines.append(f"{sha256_file(path)}  {name}  {path.stat().st_size}")
    atomic_write_text(best_dir / "sha256sums.txt", "\n".join(lines) + "\n")
    time.sleep(3.0)
    if not verify_json_files(best_dir, ["config.json", "metrics.json", "equity_curve_yearly.json"]):
        raise IOError(f"artifact json verification failed: {best_dir}")
    if not verify_hash_chain(best_dir):
        raise IOError(f"artifact hash verification failed: {best_dir}")


@dataclass
class Lot:
    symbol: str
    shares: float
    entry_idx: int
    entry_date: pd.Timestamp
    entry_px: float


@dataclass
class BuyOrder:
    symbol: str
    cash_amount: float
    signal_date: pd.Timestamp
    start_idx: int
    deadline_idx: int
    gap_threshold: float
    limit_buffer: float
    prev_close: float | None
    min_execution_value_bil: float = 0.0
    max_participation: float = 0.0
    nav_scale_bil: float = 1.0
    first_day_seen: bool = False


def read_config(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding="utf-8"))
    return dict(obj.get("config", obj))


def normalize_exchange(value) -> str:
    raw = str(value or "").upper().replace(" ", "")
    if raw in {"UPCO", "UPCOM", "UPC"}:
        return "UPCOM"
    return raw


def load_exchange_map() -> dict[str, str]:
    path = ROOT / ".cache" / "universe.parquet"
    if not path.exists():
        return {}
    try:
        df = pd.read_parquet(path)
    except Exception:
        return {}
    if "symbol" not in df.columns or "exchange" not in df.columns:
        return {}
    return {
        str(row.symbol).upper(): normalize_exchange(row.exchange)
        for row in df[["symbol", "exchange"]].dropna().itertuples(index=False)
    }


def effective_gap_threshold(symbol: str, base_gap: float, exchange_map: dict[str, str]) -> float:
    if float(base_gap) < 0:
        return float(base_gap)
    exchange = exchange_map.get(str(symbol or "").upper(), "")
    limit = PRICE_LIMIT_BY_EXCHANGE.get(exchange)
    if limit is None:
        return float(base_gap)
    return max(0.0, min(float(base_gap), limit - PRICE_LIMIT_GUARD))


def load_daily_history(symbols: list[str]) -> dict[str, pd.DataFrame]:
    hist = {}
    # 2026-05-27 override: set HISTORY_CACHE_DIR=history_2012 to use refreshed data
    import os as _os
    override = _os.environ.get("HISTORY_CACHE_DIR", "history_clean")
    base = ROOT / ".cache" / "backtest" / override
    for symbol in symbols:
        path = base / f"{symbol}.parquet"
        if not path.exists():
            continue
        df = pd.read_parquet(path)
        df["time"] = pd.to_datetime(df["time"])
        cols = ["time", "open", "high", "low", "close", "volume"]
        hist[symbol] = df.sort_values("time")[cols].reset_index(drop=True)
    return hist


def align_history_to_calendar(hist: dict[str, pd.DataFrame], dates: list[pd.Timestamp]) -> dict[str, pd.DataFrame]:
    """Forward-fill valuation prices while preserving tradability flags."""
    calendar = pd.DataFrame({"time": pd.to_datetime(dates)})
    aligned = {}
    for symbol, df in hist.items():
        x = calendar.merge(df.assign(tradable=True), on="time", how="left")
        x["tradable"] = x["tradable"].eq(True)
        x["close"] = pd.to_numeric(x["close"], errors="coerce").ffill()
        for col in ["open", "high", "low"]:
            x[col] = pd.to_numeric(x[col], errors="coerce").fillna(x["close"])
        x["volume"] = pd.to_numeric(x["volume"], errors="coerce").fillna(0.0)
        x = x.reset_index(drop=True)
        x.attrs["date_pos"] = {pd.Timestamp(d): i for i, d in enumerate(x["time"])}
        x.attrs["arrays"] = {
            "open": x["open"].to_numpy(dtype=float),
            "high": x["high"].to_numpy(dtype=float),
            "low": x["low"].to_numpy(dtype=float),
            "close": x["close"].to_numpy(dtype=float),
            "volume": x["volume"].to_numpy(dtype=float),
            "tradable": x["tradable"].to_numpy(dtype=bool),
        }
        aligned[symbol] = x
    return aligned


def load_vni_daily() -> pd.DataFrame:
    path = ROOT / ".cache" / "backtest" / "vnindex_daily.parquet"
    vni = pd.read_parquet(path)
    date_col = "date" if "date" in vni.columns else "time"
    vni[date_col] = pd.to_datetime(vni[date_col])
    vni = vni.rename(columns={date_col: "date"})
    return vni.sort_values("date").reset_index(drop=True)


def first_index_on_or_after(dates: list[pd.Timestamp], date: pd.Timestamp) -> int | None:
    idx = int(np.searchsorted(np.array(dates, dtype="datetime64[ns]"), np.datetime64(pd.Timestamp(date)), side="left"))
    if idx >= len(dates):
        return None
    return idx


def bar_for_date(hist: dict[str, pd.DataFrame], symbol: str, date: pd.Timestamp) -> pd.Series | None:
    df = hist.get(symbol)
    if df is None or df.empty:
        return None
    pos = df.attrs.get("date_pos", {}).get(pd.Timestamp(date))
    if pos is not None:
        return df.iloc[int(pos)]
    idx = int(df["time"].searchsorted(pd.Timestamp(date), side="left"))
    if idx >= len(df) or pd.Timestamp(df.iloc[idx].time) != pd.Timestamp(date):
        return None
    return df.iloc[idx]


def price_at_idx(
    hist: dict[str, pd.DataFrame],
    symbol: str,
    idx: int,
    field: str,
    *,
    require_tradable: bool = False,
) -> float | None:
    df = hist.get(symbol)
    if df is None or df.empty:
        return None
    arrays = df.attrs.get("arrays")
    if arrays:
        if idx < 0 or idx >= len(arrays["close"]):
            return None
        if require_tradable and not bool(arrays["tradable"][idx]):
            return None
        px = float(arrays[field][idx])
    else:
        if idx < 0 or idx >= len(df):
            return None
        row = df.iloc[idx]
        if require_tradable and ("tradable" in row.index and not bool(row.tradable)):
            return None
        px = float(getattr(row, field))
    return px if px > 0 and np.isfinite(px) else None


def traded_value_bil_at_idx(hist: dict[str, pd.DataFrame], symbol: str, idx: int) -> float | None:
    close_px = price_at_idx(hist, symbol, idx, "close")
    volume = price_at_idx(hist, symbol, idx, "volume")
    if close_px is None or volume is None:
        return None
    # Price is stored in thousand VND; close * volume / 1e6 gives billion VND.
    value = close_px * volume / 1_000_000.0
    return value if value >= 0 and np.isfinite(value) else None


def previous_close_at_idx(hist: dict[str, pd.DataFrame], symbol: str, idx: int) -> float | None:
    if idx <= 0:
        return None
    return price_at_idx(hist, symbol, idx - 1, "close")


def portfolio_nav_idx(cash: float, lots: dict[str, list[Lot]], hist: dict[str, pd.DataFrame], idx: int, px_field: str) -> float:
    nav = float(cash)
    for symbol, symbol_lots in lots.items():
        px = price_at_idx(hist, symbol, idx, px_field)
        if px is not None:
            nav += sum(lot.shares for lot in symbol_lots) * px
    return nav


def symbol_value_idx(lots: dict[str, list[Lot]], hist: dict[str, pd.DataFrame], symbol: str, idx: int, px_field: str) -> float:
    px = price_at_idx(hist, symbol, idx, px_field)
    if px is None:
        return 0.0
    return sum(lot.shares for lot in lots.get(symbol, [])) * px


def apply_rebalance_controls_idx(
    target_weights: dict[str, float],
    lots: dict[str, list[Lot]],
    hist: dict[str, pd.DataFrame],
    idx: int,
    nav_open: float,
    *,
    rebalance_band: float = 0.0,
    max_signal_turnover: float = 0.0,
) -> dict[str, float]:
    if nav_open <= 0 or (rebalance_band <= 0 and max_signal_turnover <= 0):
        return target_weights
    symbols = set(lots) | set(target_weights)
    current_weights = {
        symbol: symbol_value_idx(lots, hist, symbol, idx, "open") / nav_open
        for symbol in symbols
    }
    adjusted: dict[str, float] = {}
    for symbol in symbols:
        current = float(current_weights.get(symbol, 0.0))
        target = float(target_weights.get(symbol, 0.0))
        if rebalance_band > 0 and abs(target - current) <= rebalance_band:
            target = current
        adjusted[symbol] = target
    if max_signal_turnover > 0:
        deltas = {symbol: float(adjusted.get(symbol, 0.0)) - float(current_weights.get(symbol, 0.0)) for symbol in symbols}
        total_turnover = sum(abs(delta) for delta in deltas.values())
        if total_turnover > max_signal_turnover:
            scale = float(max_signal_turnover) / total_turnover
            adjusted = {
                symbol: max(0.0, float(current_weights.get(symbol, 0.0)) + delta * scale)
                for symbol, delta in deltas.items()
            }
    return {symbol: weight for symbol, weight in adjusted.items() if weight > 1e-7}


def close_for_date(hist: dict[str, pd.DataFrame], symbol: str, date: pd.Timestamp) -> float | None:
    bar = bar_for_date(hist, symbol, date)
    if bar is None:
        return None
    px = float(bar.close)
    return px if px > 0 and np.isfinite(px) else None


def open_for_date(hist: dict[str, pd.DataFrame], symbol: str, date: pd.Timestamp) -> float | None:
    bar = bar_for_date(hist, symbol, date)
    if bar is None or ("tradable" in bar.index and not bool(bar.tradable)):
        return None
    px = float(bar.open)
    return px if px > 0 and np.isfinite(px) else None


def previous_close_for_symbol(hist: dict[str, pd.DataFrame], symbol: str, date: pd.Timestamp) -> float | None:
    df = hist.get(symbol)
    if df is None or df.empty:
        return None
    idx = int(df["time"].searchsorted(pd.Timestamp(date), side="left"))
    if idx <= 0 or idx >= len(df):
        return None
    px = float(df.iloc[idx - 1].close)
    return px if px > 0 and np.isfinite(px) else None


def portfolio_nav(cash: float, lots: dict[str, list[Lot]], hist: dict[str, pd.DataFrame], date: pd.Timestamp, px_field: str) -> float:
    nav = float(cash)
    for symbol, symbol_lots in lots.items():
        bar = bar_for_date(hist, symbol, date)
        if bar is None:
            continue
        px = float(getattr(bar, px_field))
        if px > 0 and np.isfinite(px):
            nav += sum(lot.shares for lot in symbol_lots) * px
    return nav


def symbol_value(lots: dict[str, list[Lot]], hist: dict[str, pd.DataFrame], symbol: str, date: pd.Timestamp, px_field: str) -> float:
    bar = bar_for_date(hist, symbol, date)
    if bar is None:
        return 0.0
    px = float(getattr(bar, px_field))
    if px <= 0 or not np.isfinite(px):
        return 0.0
    return sum(lot.shares for lot in lots.get(symbol, [])) * px


def sell_allowed(lot: Lot, current_idx: int, min_sell_sessions: int) -> bool:
    return current_idx >= lot.entry_idx + min_sell_sessions


def sell_symbol_amount(
    lots: dict[str, list[Lot]],
    symbol: str,
    amount_value: float,
    price: float,
    current_idx: int,
    current_date: pd.Timestamp,
    min_sell_sessions: int,
    sell_cost: float,
    reason: str,
    trades: list[dict],
) -> float:
    if amount_value <= 0 or price <= 0:
        return 0.0
    symbol_lots = lots.get(symbol, [])
    remaining_value = amount_value
    cash_received = 0.0
    kept: list[Lot] = []
    for lot in symbol_lots:
        if remaining_value <= 1e-12 or not sell_allowed(lot, current_idx, min_sell_sessions):
            kept.append(lot)
            continue
        lot_value = lot.shares * price
        sell_value = min(lot_value, remaining_value)
        sell_shares = sell_value / price
        lot.shares -= sell_shares
        remaining_value -= sell_value
        proceeds = sell_shares * price * (1.0 - sell_cost)
        cash_received += proceeds
        trades.append({
            "date": current_date,
            "symbol": symbol,
            "side": "SELL",
            "shares": sell_shares,
            "price": price,
            "cash": proceeds,
            "reason": reason,
            "entry_date": lot.entry_date,
            "entry_px": lot.entry_px,
            "holding_sessions": current_idx - lot.entry_idx,
        })
        if lot.shares > 1e-12:
            kept.append(lot)
    if kept:
        lots[symbol] = kept
    elif symbol in lots:
        del lots[symbol]
    return cash_received


def execute_buy_order(
    order: BuyOrder,
    lots: dict[str, list[Lot]],
    cash: float,
    hist: dict[str, pd.DataFrame],
    date: pd.Timestamp,
    current_idx: int,
    buy_cost: float,
    trades: list[dict],
) -> tuple[float, bool, str]:
    bar = bar_for_date(hist, order.symbol, date)
    if bar is None or ("tradable" in bar.index and not bool(bar.tradable)):
        return cash, False, "missing_bar"
    open_px = float(bar.open)
    if open_px <= 0 or not np.isfinite(open_px):
        return cash, False, "bad_open"

    fill_px = None
    fill_mode = ""
    if not order.first_day_seen:
        order.first_day_seen = True
        prev_close = order.prev_close
        if prev_close and prev_close > 0:
            gap = open_px / prev_close - 1.0
            if gap <= order.gap_threshold:
                fill_px = open_px
                fill_mode = "open"

    if fill_px is None and order.prev_close and order.prev_close > 0:
        limit_px = order.prev_close * (1.0 + order.limit_buffer)
        low_px = float(bar.low)
        if low_px <= limit_px:
            fill_px = min(open_px, limit_px) if open_px <= limit_px else limit_px
            fill_mode = "pullback_limit"

    if fill_px is None:
        return cash, False, "waiting"

    spend = min(float(order.cash_amount), cash)
    if spend <= 1e-9:
        return cash, True, "no_cash"
    shares = spend / (fill_px * (1.0 + buy_cost))
    total_cost = shares * fill_px * (1.0 + buy_cost)
    cash -= total_cost
    lot = Lot(order.symbol, shares, current_idx, pd.Timestamp(date), float(fill_px))
    lots.setdefault(order.symbol, []).append(lot)
    trades.append({
        "date": date,
        "symbol": order.symbol,
        "side": "BUY",
        "shares": shares,
        "price": fill_px,
        "cash": -total_cost,
        "reason": fill_mode,
        "entry_date": date,
        "entry_px": fill_px,
        "holding_sessions": 0,
    })
    return cash, True, fill_mode


def execute_buy_order_idx(
    order: BuyOrder,
    lots: dict[str, list[Lot]],
    cash: float,
    hist: dict[str, pd.DataFrame],
    date: pd.Timestamp,
    current_idx: int,
    buy_cost: float,
    trades: list[dict],
) -> tuple[float, bool, str]:
    open_px = price_at_idx(hist, order.symbol, current_idx, "open", require_tradable=True)
    if open_px is None:
        return cash, False, "missing_bar"
    if float(order.min_execution_value_bil or 0.0) > 0:
        traded_value = traded_value_bil_at_idx(hist, order.symbol, current_idx)
        if traded_value is None or traded_value < float(order.min_execution_value_bil):
            return cash, False, "low_liq"
    if float(order.max_participation or 0.0) > 0:
        traded_value = traded_value_bil_at_idx(hist, order.symbol, current_idx)
        scaled_order_value = float(order.cash_amount) * float(order.nav_scale_bil or 1.0)
        if traded_value is None or traded_value <= 0 or scaled_order_value > traded_value * float(order.max_participation):
            return cash, False, "low_liq"

    fill_px = None
    fill_mode = ""
    if not order.first_day_seen:
        order.first_day_seen = True
        prev_close = order.prev_close
        if prev_close and prev_close > 0:
            gap = open_px / prev_close - 1.0
            if gap <= order.gap_threshold:
                fill_px = open_px
                fill_mode = "open"

    if fill_px is None and order.prev_close and order.prev_close > 0:
        limit_px = order.prev_close * (1.0 + order.limit_buffer)
        low_px = price_at_idx(hist, order.symbol, current_idx, "low")
        if low_px is not None and low_px <= limit_px:
            fill_px = min(open_px, limit_px) if open_px <= limit_px else limit_px
            fill_mode = "pullback_limit"

    if fill_px is None:
        return cash, False, "waiting"

    spend = min(float(order.cash_amount), cash)
    if spend <= 1e-9:
        return cash, True, "no_cash"
    shares = spend / (fill_px * (1.0 + buy_cost))
    total_cost = shares * fill_px * (1.0 + buy_cost)
    cash -= total_cost
    lot = Lot(order.symbol, shares, current_idx, pd.Timestamp(date), float(fill_px))
    lots.setdefault(order.symbol, []).append(lot)
    trades.append({
        "date": date,
        "symbol": order.symbol,
        "side": "BUY",
        "shares": shares,
        "price": fill_px,
        "cash": -total_cost,
        "reason": fill_mode,
        "entry_date": date,
        "entry_px": fill_px,
        "holding_sessions": 0,
    })
    return cash, True, fill_mode


def generate_targets(config_path: Path, label_dir: Path) -> tuple[dict, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    cfg = read_config(config_path)
    cfg["label_dir"] = str(label_dir)
    matrix = ds.load_matrix()
    labels = ds.load_external_labels(label_dir)
    prepared = ds.prepare_matrix(matrix, labels=labels)
    eq, holdings, _metrics = ds.run_policy(prepared, cfg)
    eq = eq.copy()
    eq["date"] = pd.to_datetime(eq["date"])
    holdings = holdings.copy()
    holdings["date"] = pd.to_datetime(holdings["date"])
    return cfg, matrix, holdings, eq


def simulate_daily(
    holdings: pd.DataFrame,
    hist: dict[str, pd.DataFrame],
    vni: pd.DataFrame,
    *,
    gap_threshold: float,
    limit_buffer: float,
    pullback_sessions: int,
    min_sell_sessions: int,
    daily_stop_loss: float,
    extra_slippage_per_side: float,
    signal_dates: list[pd.Timestamp] | None = None,
    nav0: float = 1.0,
    portfolio_vs_vni_brake_5d: float = 0.0,
    portfolio_vs_vni_brake_mult: float = 0.50,
    portfolio_vs_vni_brake_min_exposure: float = 0.80,
    portfolio_vs_vni_brake_cooldown_signals: int = 2,
    portfolio_loss_brake_5d: float = 0.0,
    min_execution_value_bil: float = 0.0,
    max_participation: float = 0.0,
    nav_scale_bil: float = 1.0,
    rebalance_band: float = 0.0,
    max_signal_turnover: float = 0.0,
    limit_floor_buffer: float | None = None,
    limit_tranches: int = 1,
    daily_max_weight_cap: float = 0.0,
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    if signal_dates is None:
        signal_dates = sorted(pd.Timestamp(x) for x in holdings["date"].dropna().unique())
    else:
        signal_dates = sorted(pd.Timestamp(x) for x in signal_dates)
    if not signal_dates:
        return pd.DataFrame(), pd.DataFrame(), {}
    start = signal_dates[0]
    end = signal_dates[-1]
    vni_full = vni.copy()
    vni = vni[(vni["date"] >= start) & (vni["date"] <= end)].copy()
    daily_dates = [pd.Timestamp(x) for x in vni["date"].tolist()]
    signal_idx_by_date = {d: i for i, d in enumerate(signal_dates)}
    signal_dates_set = set(signal_dates)
    targets_by_date = {
        pd.Timestamp(date): dict(zip(group["symbol"].astype(str), group["weight"].astype(float)))
        for date, group in holdings.groupby("date", sort=False)
    }

    cash = float(nav0)
    lots: dict[str, list[Lot]] = {}
    pending_buys: list[BuyOrder] = []
    rows: list[dict] = []
    trades: list[dict] = []
    buy_cost = 0.0015 + float(extra_slippage_per_side)
    sell_cost = 0.0025 + float(extra_slippage_per_side)
    exchange_map = load_exchange_map()
    vni_close_arr = vni["close"].astype(float).to_numpy()
    brake_signal_cooldown = 0
    brake_daily_cooldown_until = -1

    for current_idx, date in enumerate(daily_dates):
        is_signal_day = date in signal_dates_set
        if (
            (portfolio_vs_vni_brake_5d < 0 or portfolio_loss_brake_5d < 0)
            and len(rows) >= 6
            and current_idx >= 6
            and current_idx > brake_daily_cooldown_until
        ):
            nav_now = float(rows[-1]["nav"])
            nav_prev = float(rows[-6]["nav"])
            vni_now = float(vni_close_arr[current_idx - 1])
            vni_prev = float(vni_close_arr[current_idx - 6])
            current_exposure = float(rows[-1]["exposure"])
            if nav_prev > 0 and vni_prev > 0:
                portfolio_5d = nav_now / nav_prev - 1.0
                rel_5d = portfolio_5d - (vni_now / vni_prev - 1.0)
                edge_trigger = portfolio_vs_vni_brake_5d < 0 and rel_5d <= float(portfolio_vs_vni_brake_5d)
                loss_trigger = portfolio_loss_brake_5d < 0 and portfolio_5d <= float(portfolio_loss_brake_5d)
                if (edge_trigger or loss_trigger) and current_exposure >= float(portfolio_vs_vni_brake_min_exposure):
                    nav_open_for_brake = portfolio_nav_idx(cash, lots, hist, current_idx, "open")
                    target_exposure_value = nav_open_for_brake * current_exposure * float(portfolio_vs_vni_brake_mult)
                    current_exposure_value = nav_open_for_brake * current_exposure
                    sell_ratio = 0.0
                    if current_exposure_value > 0 and target_exposure_value < current_exposure_value:
                        sell_ratio = 1.0 - target_exposure_value / current_exposure_value
                    for symbol in list(lots):
                        open_px = price_at_idx(hist, symbol, current_idx, "open", require_tradable=True)
                        if open_px is None:
                            continue
                        symbol_val = symbol_value_idx(lots, hist, symbol, current_idx, "open")
                        cash += sell_symbol_amount(
                            lots,
                            symbol,
                            symbol_val * sell_ratio,
                            open_px,
                            current_idx,
                            date,
                            min_sell_sessions,
                            sell_cost,
                            "portfolio_brake",
                            trades,
                        )
                    brake_signal_cooldown = max(brake_signal_cooldown, int(portfolio_vs_vni_brake_cooldown_signals))
                    brake_daily_cooldown_until = current_idx + max(1, int(portfolio_vs_vni_brake_cooldown_signals)) * 5
        if is_signal_day:
            pending_buys = []
            if (
                (portfolio_vs_vni_brake_5d < 0 or portfolio_loss_brake_5d < 0)
                and len(rows) >= 6
                and current_idx >= 6
            ):
                nav_now = float(rows[-1]["nav"])
                nav_prev = float(rows[-6]["nav"])
                vni_now = float(vni_close_arr[current_idx - 1])
                vni_prev = float(vni_close_arr[current_idx - 6])
                current_exposure = float(rows[-1]["exposure"])
                if nav_prev > 0 and vni_prev > 0:
                    portfolio_5d = nav_now / nav_prev - 1.0
                    rel_5d = portfolio_5d - (vni_now / vni_prev - 1.0)
                    edge_trigger = portfolio_vs_vni_brake_5d < 0 and rel_5d <= float(portfolio_vs_vni_brake_5d)
                    loss_trigger = portfolio_loss_brake_5d < 0 and portfolio_5d <= float(portfolio_loss_brake_5d)
                    if (edge_trigger or loss_trigger) and current_exposure >= float(portfolio_vs_vni_brake_min_exposure):
                        brake_signal_cooldown = max(brake_signal_cooldown, int(portfolio_vs_vni_brake_cooldown_signals))
            target_weights = targets_by_date.get(date, {})
            if brake_signal_cooldown > 0 and target_weights:
                target_weights = {symbol: weight * float(portfolio_vs_vni_brake_mult) for symbol, weight in target_weights.items()}
                brake_signal_cooldown -= 1
            nav_open = portfolio_nav_idx(cash, lots, hist, current_idx, "open")
            target_weights = apply_rebalance_controls_idx(
                target_weights,
                lots,
                hist,
                current_idx,
                nav_open,
                rebalance_band=rebalance_band,
                max_signal_turnover=max_signal_turnover,
            )
            current_symbols = set(lots) | set(target_weights)

            for symbol in sorted(current_symbols):
                open_px = price_at_idx(hist, symbol, current_idx, "open", require_tradable=True)
                if open_px is None:
                    continue
                cur_value = symbol_value_idx(lots, hist, symbol, current_idx, "open")
                target_value = nav_open * float(target_weights.get(symbol, 0.0))
                if cur_value > target_value + nav_open * 0.001:
                    cash += sell_symbol_amount(
                        lots,
                        symbol,
                        cur_value - target_value,
                        open_px,
                        current_idx,
                        date,
                        min_sell_sessions,
                        sell_cost,
                        "rebalance",
                        trades,
                    )

            nav_after_sells = portfolio_nav_idx(cash, lots, hist, current_idx, "open")
            buy_specs = []
            for symbol, weight in sorted(target_weights.items(), key=lambda kv: -kv[1]):
                cur_value = symbol_value_idx(lots, hist, symbol, current_idx, "open")
                target_value = nav_after_sells * float(weight)
                buy_value = max(0.0, target_value - cur_value)
                if buy_value > nav_after_sells * 0.001:
                    buy_specs.append((symbol, buy_value))
            total_buy = sum(v for _, v in buy_specs)
            scale = min(1.0, cash / total_buy) if total_buy > 0 else 0.0
            for symbol, buy_value in buy_specs:
                start_idx = current_idx
                deadline_idx = min(len(daily_dates) - 1, current_idx + max(1, pullback_sessions) - 1)
                prev_close = previous_close_at_idx(hist, symbol, current_idx)
                tranche_count = max(1, int(limit_tranches or 1))
                if tranche_count == 1:
                    levels = [float(limit_buffer)]
                else:
                    floor = float(limit_floor_buffer if limit_floor_buffer is not None else limit_buffer)
                    levels = [float(x) for x in np.linspace(float(limit_buffer), floor, tranche_count)]
                for level in levels:
                    pending_buys.append(BuyOrder(
                        symbol=symbol,
                        cash_amount=buy_value * scale / tranche_count,
                        signal_date=date,
                        start_idx=start_idx,
                        deadline_idx=deadline_idx,
                        gap_threshold=effective_gap_threshold(symbol, level, exchange_map),
                        limit_buffer=level,
                        prev_close=prev_close,
                        min_execution_value_bil=float(min_execution_value_bil),
                        max_participation=float(max_participation),
                        nav_scale_bil=float(nav_scale_bil),
                    ))

        still_pending = []
        for order in pending_buys:
            if current_idx < order.start_idx:
                still_pending.append(order)
                continue
            if current_idx > order.deadline_idx:
                trades.append({
                    "date": date,
                    "symbol": order.symbol,
                    "side": "MISS_BUY",
                    "shares": 0.0,
                    "price": np.nan,
                    "cash": 0.0,
                    "reason": "expired_no_pullback",
                    "entry_date": pd.NaT,
                    "entry_px": np.nan,
                    "holding_sessions": 0,
                })
                continue
            cash, done, reason = execute_buy_order_idx(order, lots, cash, hist, date, current_idx, buy_cost, trades)
            if not done and reason in {"waiting", "low_liq"}:
                still_pending.append(order)
        pending_buys = still_pending

        if daily_stop_loss > 0:
            for symbol in list(lots):
                if price_at_idx(hist, symbol, current_idx, "open", require_tradable=True) is None:
                    continue
                kept: list[Lot] = []
                stop_cash = 0.0
                for lot in lots.get(symbol, []):
                    if not sell_allowed(lot, current_idx, min_sell_sessions):
                        kept.append(lot)
                        continue
                    stop_px = lot.entry_px * (1.0 - daily_stop_loss)
                    open_px = price_at_idx(hist, symbol, current_idx, "open") or 0.0
                    low_px = price_at_idx(hist, symbol, current_idx, "low") or np.inf
                    if low_px <= stop_px:
                        fill_px = open_px if open_px <= stop_px else stop_px
                        proceeds = lot.shares * fill_px * (1.0 - sell_cost)
                        stop_cash += proceeds
                        trades.append({
                            "date": date,
                            "symbol": symbol,
                            "side": "SELL",
                            "shares": lot.shares,
                            "price": fill_px,
                            "cash": proceeds,
                            "reason": "daily_stop",
                            "entry_date": lot.entry_date,
                            "entry_px": lot.entry_px,
                            "holding_sessions": current_idx - lot.entry_idx,
                        })
                    else:
                        kept.append(lot)
                cash += stop_cash
                if kept:
                    lots[symbol] = kept
                elif symbol in lots:
                    del lots[symbol]

        if daily_max_weight_cap and daily_max_weight_cap > 0:
            nav_close_for_cap = portfolio_nav_idx(cash, lots, hist, current_idx, "close")
            if nav_close_for_cap > 0:
                for symbol in list(lots):
                    close_px = price_at_idx(hist, symbol, current_idx, "close", require_tradable=True)
                    if close_px is None:
                        continue
                    symbol_val = symbol_value_idx(lots, hist, symbol, current_idx, "close")
                    allowed_value = nav_close_for_cap * float(daily_max_weight_cap)
                    if symbol_val > allowed_value + nav_close_for_cap * 0.001:
                        cash += sell_symbol_amount(
                            lots,
                            symbol,
                            symbol_val - allowed_value,
                            close_px,
                            current_idx,
                            date,
                            min_sell_sessions,
                            sell_cost,
                            "daily_weight_cap",
                            trades,
                        )

        nav_close = portfolio_nav_idx(cash, lots, hist, current_idx, "close")
        exposure = 0.0
        for symbol in lots:
            exposure += symbol_value_idx(lots, hist, symbol, current_idx, "close")
        exposure = exposure / nav_close if nav_close > 0 else 0.0
        rows.append({
            "date": date,
            "nav": nav_close,
            "cash": cash,
            "exposure": exposure,
            "pending_buy_count": len(pending_buys),
            "position_count": len(lots),
            "is_signal_day": is_signal_day,
            "signal_seq": signal_idx_by_date.get(date, np.nan),
        })

    eq = pd.DataFrame(rows)
    if not eq.empty:
        eq["strat_ret_5d"] = eq["nav"].astype(float).pct_change(5)
        if len(vni) == len(eq):
            eq["vni_ret_5d"] = vni["close"].astype(float).reset_index(drop=True).pct_change(5)
    trades_df = pd.DataFrame(trades)
    metrics = add_daily_vni30_metrics(eq, vni, canonical_vni=vni_full)
    return eq, trades_df, metrics


def add_daily_vni30_metrics(eq: pd.DataFrame, vni: pd.DataFrame, canonical_vni: pd.DataFrame | None = None) -> dict:
    eq = eq.copy()
    eq["date"] = pd.to_datetime(eq["date"])
    eq = eq.sort_values("date").reset_index(drop=True)
    if canonical_vni is None:
        canonical_vni = vni
    canonical_vni = canonical_vni.copy()
    canonical_vni["date"] = pd.to_datetime(canonical_vni["date"])
    canonical_vni = canonical_vni.sort_values("date").reset_index(drop=True)
    yearly = {}
    for year, group in eq.groupby(eq["date"].dt.year):
        year = int(year)
        if 2021 <= year <= 2026 and len(group) > 1:
            prev = eq[eq["date"] < pd.Timestamp(f"{year}-01-01")]
            base_nav = float(prev["nav"].iloc[-1]) if not prev.empty else float(group["nav"].iloc[0])
            if base_nav > 0:
                yearly[year] = (float(group["nav"].iloc[-1]) / base_nav - 1.0) * 100.0
    vni_ret = {}
    for year in range(2021, 2027):
        eq_group = eq[eq["date"].dt.year == year]
        if eq_group.empty:
            continue
        end_date = pd.Timestamp(eq_group["date"].iloc[-1])
        prev_vni = canonical_vni[canonical_vni["date"] < pd.Timestamp(f"{year}-01-01")]
        year_vni = canonical_vni[
            (canonical_vni["date"].dt.year == year)
            & (canonical_vni["date"] <= end_date)
        ]
        if year_vni.empty:
            continue
        base_close = float(prev_vni["close"].iloc[-1]) if not prev_vni.empty else float(year_vni["close"].iloc[0])
        if base_close > 0:
            vni_ret[year] = (float(year_vni["close"].iloc[-1]) / base_close - 1.0) * 100.0
    nav = eq["nav"].astype(float)
    ret = nav.pct_change().fillna(0.0)
    yrs = (eq["date"].iloc[-1] - eq["date"].iloc[0]).days / 365.25
    cagr = (nav.iloc[-1] / nav.iloc[0]) ** (1 / yrs) - 1 if yrs > 0 and nav.iloc[0] > 0 else np.nan
    maxdd = (nav / nav.cummax() - 1).min()
    sharpe = ret.mean() / ret.std() * np.sqrt(252) if ret.std() > 0 else 0.0
    metrics = {
        "cagr": cagr * 100.0,
        "maxdd": maxdd * 100.0,
        "sharpe": float(sharpe),
        "pass30": 0,
        "pass_vni30": 0,
        "min_edge_vs_vni": np.nan,
        "min_gap_to_vni30": np.nan,
    }
    edges = []
    pass30 = 0
    pass_vni30 = 0
    for year in range(2021, 2027):
        strategy = float(yearly.get(year, np.nan))
        vni_y = float(vni_ret.get(year, np.nan))
        edge = strategy - vni_y if pd.notna(strategy) and pd.notna(vni_y) else np.nan
        metrics[f"y{year}"] = strategy
        metrics[f"vni_y{year}"] = vni_y
        metrics[f"edge_y{year}"] = edge
        metrics[f"pass_vni30_y{year}"] = bool(pd.notna(edge) and edge >= 30.0)
        if pd.notna(strategy) and strategy >= 30.0:
            pass30 += 1
        if pd.notna(edge):
            edges.append(edge)
            if edge >= 30.0:
                pass_vni30 += 1
    metrics["pass30"] = pass30
    metrics["pass_vni30"] = pass_vni30
    if edges:
        metrics["min_edge_vs_vni"] = float(min(edges))
        metrics["min_gap_to_vni30"] = float(min(edges) - 30.0)
    return metrics


def write_outputs(out_dir: Path, best: dict, results: pd.DataFrame, best_eq: pd.DataFrame, best_trades: pd.DataFrame) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    best_dir = out_dir / "best_stock_only"
    best_dir.mkdir(parents=True, exist_ok=True)
    for attempt in range(2):
        atomic_write_csv(results, out_dir / "execution_results.csv", index=False)
        atomic_write_parquet(best_eq, best_dir / "equity_curve_honest.parquet", index=False)
        atomic_write_csv(best_trades, best_dir / "daily_execution_trades.csv", index=False)
        atomic_write_text(best_dir / "config.json", json.dumps(best, indent=2, default=str))
        time.sleep(3.0)
        write_companion_integrity_files(best_dir, best, best_eq, best_trades)
        if verify_saved_outputs(best_dir, best):
            break
        if attempt == 1:
            raise IOError(f"saved daily execution artifacts failed verification: {best_dir}")
    lines = [
        "# Daily Execution Latency Search",
        "",
        f"Best beat VNI +30pp: {int(best['metrics']['pass_vni30'])}/6",
        f"Min edge vs VNI: {float(best['metrics']['min_edge_vs_vni']):.2f}pp",
        f"CAGR: {float(best['metrics']['cagr']):.2f}%",
        f"MaxDD: {float(best['metrics']['maxdd']):.2f}%",
        f"Base gap threshold: {float(best['execution']['gap_threshold']) * 100:.2f}% (price-limit aware; HOSE capped at {(PRICE_LIMIT_BY_EXCHANGE['HOSE'] - PRICE_LIMIT_GUARD) * 100:.2f}%)",
        f"Limit buffer: {float(best['execution']['limit_buffer']) * 100:.2f}%",
        f"Pullback sessions: {int(best['execution']['pullback_sessions'])}",
        f"Min sell sessions: {int(best['execution']['min_sell_sessions'])}",
        f"Daily stop loss: {float(best['execution']['daily_stop_loss']) * 100:.2f}%",
        "",
        "| Year | Return | Edge vs VNI | Pass? |",
        "|---|---:|---:|---|",
    ]
    for year in range(2021, 2027):
        lines.append(
            f"| {year} | {float(best['metrics'][f'y{year}']):.1f}% | "
            f"{float(best['metrics'][f'edge_y{year}']):.1f}pp | "
            f"{'YES' if best['metrics'][f'pass_vni30_y{year}'] else 'NO'} |"
        )
    atomic_write_text(out_dir / "summary.md", "\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    ap.add_argument("--label-dir", type=Path, default=DEFAULT_LABEL_DIR)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--gap-thresholds", default="0.03,0.05,0.07,0.09")
    ap.add_argument("--limit-buffers", default="0,0.005,0.01")
    ap.add_argument("--pullback-sessions", default="2,3,4,5,7")
    ap.add_argument("--min-sell-sessions", default="3")
    ap.add_argument("--daily-stop-losses", default="0,0.04,0.06,0.08,0.10")
    ap.add_argument("--extra-slippage-per-side", type=float, default=0.0015)
    args = ap.parse_args()

    cfg, matrix, holdings, weekly_eq = generate_targets(args.config, args.label_dir)
    symbols = sorted(set(holdings["symbol"].astype(str)))
    hist = load_daily_history(symbols)
    vni = load_vni_daily()
    signal_dates = sorted(pd.Timestamp(x) for x in weekly_eq["date"].dropna().unique())
    if signal_dates:
        daily_dates = [
            pd.Timestamp(x)
            for x in vni[(vni["date"] >= signal_dates[0]) & (vni["date"] <= signal_dates[-1])]["date"].tolist()
        ]
        hist = align_history_to_calendar(hist, daily_dates)
    gaps = [float(x) for x in args.gap_thresholds.split(",") if x.strip()]
    buffers = [float(x) for x in args.limit_buffers.split(",") if x.strip()]
    pullbacks = [int(x) for x in args.pullback_sessions.split(",") if x.strip()]
    min_sells = [int(x) for x in args.min_sell_sessions.split(",") if x.strip()]
    stops = [float(x) for x in args.daily_stop_losses.split(",") if x.strip()]

    rows = []
    best_score = -1e18
    best_payload = None
    run_id = 0
    for gap in gaps:
        for buffer in buffers:
            for pullback in pullbacks:
                for min_sell in min_sells:
                    for stop in stops:
                        eq, trades, metrics = simulate_daily(
                            holdings,
                            hist,
                            vni,
                            gap_threshold=gap,
                            limit_buffer=buffer,
                            pullback_sessions=pullback,
                            min_sell_sessions=min_sell,
                            daily_stop_loss=stop,
                            extra_slippage_per_side=args.extra_slippage_per_side,
                            signal_dates=signal_dates,
                            nav0=1.0,
                            portfolio_vs_vni_brake_5d=float(cfg.get("portfolio_vs_vni_brake_5d", 0.0) or 0.0),
                            portfolio_vs_vni_brake_mult=float(cfg.get("portfolio_vs_vni_brake_mult", 0.50) or 0.50),
                            portfolio_vs_vni_brake_min_exposure=float(cfg.get("portfolio_vs_vni_brake_min_exposure", 0.80) or 0.80),
                            portfolio_vs_vni_brake_cooldown_signals=int(cfg.get("portfolio_vs_vni_brake_cooldown_signals", 2) or 2),
                            portfolio_loss_brake_5d=float(cfg.get("portfolio_loss_brake_5d", 0.0) or 0.0),
                        )
                        row = {
                            "run_id": run_id,
                            "gap_threshold": gap,
                            "limit_buffer": buffer,
                            "pullback_sessions": pullback,
                            "min_sell_sessions": min_sell,
                            "daily_stop_loss": stop,
                            **metrics,
                            "avg_exposure": float(eq["exposure"].mean()) if not eq.empty else 0.0,
                            "trade_count": int(len(trades)),
                        }
                        rows.append(row)
                        score = (
                            float(metrics.get("pass_vni30", 0)) * 1_000_000
                            + float(metrics.get("min_gap_to_vni30", -999)) * 200_000
                            + float(metrics.get("cagr", 0)) * 500
                            - abs(float(metrics.get("maxdd", -100))) * 800
                        )
                        if score > best_score:
                            best_score = score
                            best_payload = {
                                "base_config": str(args.config),
                                "base_policy_config": cfg,
                                "execution": {
                                    "gap_threshold": gap,
                                    "limit_buffer": buffer,
                                    "pullback_sessions": pullback,
                                    "min_sell_sessions": min_sell,
                                    "daily_stop_loss": stop,
                                    "extra_slippage_per_side": args.extra_slippage_per_side,
                                },
                                "metrics": metrics,
                            }, eq, trades
                            print(
                                f"BEST {run_id}: vni30={metrics['pass_vni30']} "
                                f"min_edge={metrics['min_edge_vs_vni']:.1f} cagr={metrics['cagr']:.1f} "
                                f"dd={metrics['maxdd']:.1f} gap={gap:.2f} buf={buffer:.3f} "
                                f"wait={pullback} min_sell={min_sell} stop={stop:.2f}",
                                flush=True,
                            )
                        run_id += 1

    results = pd.DataFrame(rows).sort_values(
        ["pass_vni30", "min_gap_to_vni30", "cagr"],
        ascending=[False, False, False],
    )
    if best_payload is not None:
        write_outputs(args.out_dir, best_payload[0], results, best_payload[1], best_payload[2])
    else:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        atomic_write_csv(results, args.out_dir / "execution_results.csv", index=False)


if __name__ == "__main__":
    main()
